---
/**:
  ros__parameters:
    heracles_ip: $(env HERACLES_IP)
    heracles_port: $(env HERACLES_PORT)
    heracles_neo4j_user: $(env HERACLES_NEO4J_USERNAME)
    heracles_neo4j_pass: $(env HERACLES_NEO4J_PASSWORD)
    object_labelspace: ade20k_mit_label_space.yaml
    region_labelspace: b45_label_space.yaml
